// This file is here to satisfy TypeScript module resolution.
export const BOARD_SIZE = 5;
export const FREE_SPACE = "FREE SPACE";
export const MAX_PLAYERS = 10;
export const MAX_PHRASES = 25;
export const MAX_PHRASE_LENGTH = 50;
export const MAX_PHRASE_LIST_NAME_LENGTH = 50;
export const MAX_PHRASE_LIST_DESCRIPTION_LENGTH = 200;
export const MAX_CHAT_MESSAGE_LENGTH = 200;
export const MAX_CHAT_MESSAGES = 100;
export const MAX_PLAYER_NAME_LENGTH = 20;
export const MAX_ROOM_NAME_LENGTH = 50;
export const MAX_ROOM_DESCRIPTION_LENGTH = 200;
export const MAX_ROOM_PASSWORD_LENGTH = 20;
export const MAX_ROOM_CAPACITY = 20;
export const MAX_ROOM_DURATION = 24; // hours
export const MAX_ROOM_INACTIVITY = 30; // minutes
export const MAX_ROOM_MESSAGES = 1000;
export const MAX_ROOM_PLAYERS = 20;
export const MAX_ROOM_PHRASE_LISTS = 10;
export const MAX_ROOM_GAMES = 10;
export const MAX_ROOM_CHAT_MESSAGES = 1000;
export const MAX_ROOM_CHAT_MESSAGE_LENGTH = 200;
export const MAX_ROOM_CHAT_MESSAGE_HISTORY = 100;
export const MAX_ROOM_CHAT_MESSAGE_RATE = 10; // messages per minute
export const MAX_ROOM_CHAT_MESSAGE_INTERVAL = 1000; // milliseconds
export const MAX_ROOM_CHAT_MESSAGE_COOLDOWN = 1000; // milliseconds
export const MAX_ROOM_CHAT_MESSAGE_BURST = 5; // messages
export const MAX_ROOM_CHAT_MESSAGE_BURST_INTERVAL = 5000; // milliseconds
export const MAX_ROOM_CHAT_MESSAGE_BURST_COOLDOWN = 10000; // milliseconds
export const MAX_ROOM_CHAT_MESSAGE_BURST_PENALTY = 30000; // milliseconds
export const MAX_ROOM_CHAT_MESSAGE_BURST_PENALTY_DURATION = 300000; // milliseconds
export const MAX_ROOM_CHAT_MESSAGE_BURST_PENALTY_MULTIPLIER = 2; // multiplier
export const MAX_ROOM_CHAT_MESSAGE_BURST_PENALTY_MAX = 300000; // milliseconds
export const MAX_ROOM_CHAT_MESSAGE_BURST_PENALTY_MIN = 1000; // milliseconds
export const MAX_ROOM_CHAT_MESSAGE_BURST_PENALTY_STEP = 1000; // milliseconds
export const MAX_ROOM_CHAT_MESSAGE_BURST_PENALTY_INITIAL = 1000; // milliseconds
export const MAX_ROOM_CHAT_MESSAGE_BURST_PENALTY_MAX_MULTIPLIER = 10; // multiplier
export const MAX_ROOM_CHAT_MESSAGE_BURST_PENALTY_MIN_MULTIPLIER = 1; // multiplier
export const MAX_ROOM_CHAT_MESSAGE_BURST_PENALTY_STEP_MULTIPLIER = 1; // multiplier
export const MAX_ROOM_CHAT_MESSAGE_BURST_PENALTY_INITIAL_MULTIPLIER = 1; // multiplier
export const MAX_ROOM_CHAT_MESSAGE_BURST_PENALTY_MAX_DURATION = 300000; // milliseconds
export const MAX_ROOM_CHAT_MESSAGE_BURST_PENALTY_MIN_DURATION = 1000; // milliseconds
export const MAX_ROOM_CHAT_MESSAGE_BURST_PENALTY_STEP_DURATION = 1000; // milliseconds
export const MAX_ROOM_CHAT_MESSAGE_BURST_PENALTY_INITIAL_DURATION = 1000; // milliseconds
export const MAX_ROOM_CHAT_MESSAGE_BURST_PENALTY_MAX_STEP = 1000; // milliseconds
export const MAX_ROOM_CHAT_MESSAGE_BURST_PENALTY_MIN_STEP = 1000; // milliseconds
export const MAX_ROOM_CHAT_MESSAGE_BURST_PENALTY_STEP_STEP = 1000; // milliseconds
export const MAX_ROOM_CHAT_MESSAGE_BURST_PENALTY_INITIAL_STEP = 1000; // milliseconds
export const MAX_ROOM_CHAT_MESSAGE_BURST_PENALTY_MAX_INITIAL = 1000; // milliseconds
export const MAX_ROOM_CHAT_MESSAGE_BURST_PENALTY_MIN_INITIAL = 1000; // milliseconds
export const MAX_ROOM_CHAT_MESSAGE_BURST_PENALTY_STEP_INITIAL = 1000; // milliseconds
export const MAX_ROOM_CHAT_MESSAGE_BURST_PENALTY_INITIAL_INITIAL = 1000; // milliseconds 